version: 1.2.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
branches:
  only:
    - master
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
test:
  categories:
    only:
    - Unit
deploy:
- provider: NuGet
  api_key:
    secure: 8GQgV2DHU3qdilEMg9OZqXx6RfeZUVWjsbXgj1b8xP4lqY4Xrn4fY/wMriMI7HN0