version: 2.1.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
branches:
  only:
    - master
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
test:
  categories:
    only:
    - Unit
deploy:
- provider: NuGet
  api_key:
    secure: oy2p7vkrztr7gli5uipars2uz2xmppoudlssqzo5bj7mva